package lehrtools.viewmodel.information;

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.SimpleBooleanProperty;

import java.util.ArrayList;

/**
 *  Class that is used to  pass information in between the
 *  View and the ViewModel. This Class generated by Line_Factory class and
 *  its content from a Step_DP instance. It contains the first Step of the algorithm,
 *  which is the original formula and the reason that it does not contain any calculations.
 */
public class Line_Simple extends Line {
    /**
     * Contains a String representation of each clause from a formula.
     */
    public ArrayList<String> clauses;
    /**
     * List signals the view if a clause is to be displayed as selected or not.
     */
    public ArrayList<BooleanProperty> selected;

    /**
     * Constructor
     * @param label String representation of the type from the Step subclass instance it was created.
     * @param step_description Description of the Step subclass instance it was created.
     * @param clauses String representation of each clause from a formula.
     */
    public Line_Simple(String label,
                       String step_description ,
                       ArrayList<String> clauses) {
        super(label, step_description);
        this.clauses = clauses;
        selected = new ArrayList<>();
        for(int i = 0; i<clauses.size();i++)
            selected.add(new SimpleBooleanProperty(false));
    }
}
