package lehrtools.viewmodel.information;

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.SimpleBooleanProperty;

import java.util.ArrayList;

/**
 *  Class that is used to  pass information in between the
 *  View and the ViewModel. This Class generated by Line_Factory class is use
 *  only in the DP60 algorithm to store the results of any of teh steps it executes.
 */
public class Line_DP60 extends Line
{
    /**
     * The name of the formula
     */
    public final String step;
    /**
     * String representation of each clause from a formula.
     */
    public final ArrayList<String> clauses;
    /**
     * The List of calculations corresponding to that Step.
     */
    public final ArrayList<ArrayList<String>> calculations_info;
    /**
     * List signals the view if a clause is to be displayed as selected or not.
     */
    public final ArrayList<BooleanProperty> selected;

    /**
     * Constructor
     * @param label String representation of the type from the Step subclass instance it was created.
     * @param step The name of the formula.
     * @param step_description Description of the Step subclass instance it was created.
     * @param clauses String representation of each clause from a formula.
     * @param calculations_info The List of calculations corresponding to that Step.
     */
    public Line_DP60(String label ,
                     String step,
                     String step_description,
                     ArrayList<String> clauses,
                     ArrayList<ArrayList<String>> calculations_info
                     )
    {
        super(label, step_description);
        this.step = step;
        this.clauses = clauses;
        this.calculations_info = calculations_info;
        selected = new ArrayList<>();
        for(String clause :clauses)
            selected.add(new SimpleBooleanProperty(false));


    }


}
