package lehrtools.viewmodel.information;

/**
 * Base Class that is used to  pass information in between the
 * View and the ViewModel. This Class generated by Line_Factory class and
 * its content is always taken from a Step subclass. The View uses this class
 * generate the content it displays by using the HBox_Factory class.
 */
public class Line {
	/**
	 * String representation of the type from the Step subclass instance it was created.
	 */
	public  final String label;
	/**
	 * Description of the Step subclass instance it was created.
	 */
	public  final String step_description;
	
	public Line(String label , String step_description )
	{
		this.label = label;
		this.step_description = step_description;
	}

}
