package lehrtools.viewmodel.information;

import java.util.ArrayList;

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.SimpleBooleanProperty;
/**
 *  Class that is used to  pass information in between the
 *  View and the ViewModel. This Class generated by Line_Factory class and
 *  takes the Values for the last Step of an iteration for the Resolution step.
 *  It contains the new Formula reaolvents are goint to be derived from, thats why this
 *  Line does not contain any calculations.
 */
public class Line_Composite extends Line {
	/**
	 * String representation of each clause from a formula.
	 */
	public ArrayList<String> clauses;
	/**
	 * List signals the view if a clause is to be displayed as selected or not.
	 */
	public ArrayList<BooleanProperty> clause_selected;

	/**
	 * Constructor
	 * @param label String representation of the type from the Step subclass instance it was created.
	 * @param formula_name he name of the formula, usually Res(F)_i or R_i.
	 * @param clauses String representation of each clause from a formula.
	 */
	public Line_Composite(String label , 
						  String formula_name,
						  ArrayList<String> clauses)
	{
		super(label, formula_name);
		this.clause_selected = new ArrayList<>();
		this.clauses = clauses;
		for(int i =0; i < clauses.size();i++)
			clause_selected.add(new SimpleBooleanProperty(false));
	}

}
